### ISSUE TITLE
Lab3 预加载解决方案

### ISSUE THREAD

**Issue by AlanHN** [HaoYuan-Hu/ByteDanceLab#1]
Lab3 的预加载问题可以通过函数`pager.setOffscreenPageLimit(0)`解决，
详见https://github.com/AlanHN/bytedance-android-camp-sjtu-2021/blob/d3e39c93d0a74af0fbba2964bae8066a2ebb50e9/Homework-Chapter-3/Homework/app/src/main/java/com/example/chapter3/homework/Ch3Ex3Activity.java#L47

**Comment by HaoYuan-Hu** [comment]
md，作业都交了，咋不早点跟我说

**Comment by AlanHN** [comment]
Done

**Comment by AlanHN** [comment]
Done
